Workflow UI creation
digital-ai/backstage-release pull request #67
Opened 2024-11-13 11:24 UTC by Karthigaiselvan

## Release Checklist

- All steps below must be completed prior to merging.

## Changes Made

- Please note all changes made to API, design, functionality, etc.

## Author Checklist

### Required

- [ ] PR title should follow correct format.
  - MAJOR Release is used when there are breaking changes involved
  - MINOR Release is used when enhancements are introduced
  - PATCH Release is used for defects, security, tech chores, etc.
  - pre-alpha is used for testing releases
  - Note:
    - Based on the commit messages, increment the version from the latest release.
    - Push the bumped npm version in package.json back into the repo.
    - Push a tag for the new version back into the repo.
    - [For more details on versioning](https://github.com/phips28/gh-action-bump-version/blob/master/README.md) 
- [ ] Checklist of **changes made** added to PR description
- [ ] Related issue(s) linked to PR

 
## Reviewer Checklist

- [ ] Author checklist has been reviewed?
- [ ] All acceptance criteria has been met from linked issue
- [ ] Run code locally and verify all changes

## Related Issue(s)

Resolves #XXXX
Story-######
Defect-######

2024-11-29 06:56 UTC, nitheshrayuduv approved these changes
Looks good to me :)

2024-12-02 03:03 UTC, sishwarya requested changes

2024-12-02 03:03 UTC, sishwarya commented on plugins/dai-release/src/components/WorkflowCatalogComponent/WorkflowCatalogComponent.test.tsx
> +      loadMoreData: jest.fn(),
Cover the worst-case scenario when there is no data.

2024-12-02 11:44 UTC, Karthigaiselvan commented on plugins/dai-release/src/components/WorkflowComponent/WorkflowComponent.test.tsx
> +    expect(screen.getByText('Workflow catalog')).toBeInTheDocument();
With and without data cases added. Error scenarios will be added in API implementation story

2024-12-04 07:16 UTC, merged